#brew 'nvm'
brew 'ag'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'cask'
brew 'cmake' # build youcompleteme
brew 'coreutils'
brew 'ctags'
brew 'fzf'
brew 'git'
brew 'go'
brew 'jq'
brew 'pssh'
brew 'python3'
brew 'rbenv'
brew 'reattach-to-user-namespace' # connect tmux to the OS X clipboard service
brew 'shellcheck'
brew 'tmux'
brew 'vim'
brew 'yarn'

# gui apps
# cask 'google-chrome'
# cask 'docker'
