#brew 'nvm'
brew 'awscli'
brew 'ag'
brew 'bash'
brew 'bash-completion'
brew 'cask'
# build youcompleteme
brew 'cmake'
brew 'coreutils'
brew 'ctags'
brew 'fzf'
brew 'git'
brew 'jq'
brew 'node'
brew 'python3'
brew 'rbenv'
# connect tmux to the OS X clipboard service
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'vim'
brew 'yarn'

# gui apps
cask 'google-chrome'
cask 'docker'
