brew 'ag'
brew 'bash'
brew 'bash-completion'
brew 'ctags'
brew 'git'
brew 'jq'
brew 'nvm'
brew 'python3'
brew 'rbenv'
# connect tmux to the OS X clipboard service
brew 'reattach-to-user-namespace' 
brew 'tmux'
brew 'vim'
