#!/usr/bin/env bash

###############################################################################################
# Setup script for MacOS. This configures system and application settings.
#
# Run:
#
# ./macos
###############################################################################################

### System

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Tab through UI
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Automatically show and hide the dock
defaults write com.apple.dock autohide -bool true

# Tile Left/Right and Zoom (maximize without fullscreen)
# @      = CMD
# ^      = Control
# \U2190 = Left Arrow
# \U2192 = Right Arrow
# \U2191 = Right Arrow
defaults write -g NSUserKeyEquivalents -dict-add 'Move Window to Left Side of Screen'  '@^\U2190'
defaults write -g NSUserKeyEquivalents -dict-add 'Move Window to Right Side of Screen' '@^\U2192'
defaults write -g NSUserKeyEquivalents -dict-add 'Zoom'                                '@^\U2191'

### Applications

## Chrome

# Disable google chrome swipe
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE

### End

echo 'Restart your computer to see MacOS changes take effect.'
