#!/usr/bin/env bash

# Setup script for MacOS
#
# Run:
#
# ./macos

# disable google chrome swipe
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE

# show hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# tab through UI
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
