#!/usr/bin/env bash

# Setup script for MacOS
#
# Run:
#
# ./macos

# Disable google chrome swipe
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Tab through UI
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Tile Left/Right
# @      = CMD
# ^      = Control
# \U2190 = Left Arrow
# \U2192 = Right Arrow
defaults write -g NSUserKeyEquivalents -dict-add 'Move Window to Left Side of Screen' '@^\U2190'
defaults write -g NSUserKeyEquivalents -dict-add 'Move Window to Right Side of Screen' '@^\U2192'
